set client_min_messages to warning;

-- DANGER: this is NOT how to do it in the real world.
-- `drop schema` INSTANTLY ERASES EVERYTHING.
drop schema "public" cascade;

create schema "public";

CREATE TABLE "users" (
  "userId" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar,
  "password" varchar,
  "createdAt" timestamptz
);

CREATE TABLE "products" (
  "productId" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "productName" varchar,
  "description" varchar,
  "imageUrl" varchar,
  "price" decimal(10,2)
);

CREATE TABLE "cartItems" (
  "cartId" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId" integer,
  "productId" integer,
  "quantity" integer,
  "addedAt" timestamptz
);

ALTER TABLE "cartItems" ADD FOREIGN KEY ("userId") REFERENCES "users" ("userId");

ALTER TABLE "cartItems" ADD FOREIGN KEY ("productId") REFERENCES "products" ("productId");
